name: 'Setup Node'
description: 'Setup Node.js'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  cache:
    description: 'Cache type'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      shell: bash
      run: |
        curl -fsSL https://deb.nodesource.com/setup_${{ inputs.node-version }}.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node --version 