name: 'Deploy Pages'
description: 'Deploy to GitHub Pages'
runs:
  using: "composite"
  steps:
    - name: Deploy to GitHub Pages
      shell: bash
      run: |
        echo "::set-output name=page_url::https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" 