name: 'Checkout'
description: 'Checkout repository'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      shell: bash
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.sha }} 