name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
      
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build
        env:
          NEXT_PUBLIC_BASE_PATH: '/pass-the-plate'
          NODE_ENV: 'production'
      
      - name: Setup Pages
        uses: ./.github/actions/configure-pages
        with:
          static_site_generator: next
      
      - name: Upload artifact
        uses: ./.github/actions/upload-pages-artifact
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: ./.github/actions/deploy-pages 